<h2 align="justify">Pol&iacute;tica de Privacidad</h2>
<p align="justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; De conformidad a lo dispuesto en&nbsp;la Constituci&oacute;n Pol&iacute;tica de la Rep&uacute;blica, art&iacute;culo 19 N&ordm; 4 y la Ley N&ordm; 19.628 sobre Protecci&oacute;n de la Vida Privada se se&ntilde;ala lo siguiente: <br />

Este organismo, pone en conocimiento de todos quienes acceden a este Sistema de Gesti&oacute;n de Solicitudes la siguiente Pol&iacute;tica de Privacidad, a fin de resguardar la seguridad, confidencialidad y privacidad del usuario y/o visitante de este sitio, as&iacute; como de establecer los t&eacute;rminos de uso del Sistema de Gesti&oacute;n de Solicitudes de Informaci&oacute;n P&uacute;blica Ley N&deg;20.285. <br />
Estas pol&iacute;ticas tienen por finalidad asegurar la correcta utilizaci&oacute;n de la informaci&oacute;n recopilada a trav&eacute;s de las visitas de este sitio y de sus contenidos.</p>

<p align="justify"><strong>I. EN CUANTO A LA RECOPILACION DE DATOS</strong></p>
<p align="justify">Este organismo&nbsp;recopila datos de los suscriptores, usuarios y/o visitantes que hagan uso de este portal, a trav&eacute;s de dos mecanismos: <br />
a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Mecanismos Autom&aacute;ticos: Son aquellos procesos inform&aacute;ticos realizados para generar registros de las actividades de los visitantes de sitios Web y cuyo objeto es establecer patrones de actividad, navegaci&oacute;n y audiencia, que no implican la identificaci&oacute;n personal de aquellos suscriptores, usuarios y/o visitantes que accedan a los servicios del sistema de gesti&oacute;n de solicitudes. <br />
A este organismo, s&oacute;lo en lo que le concierne administrar, se reserva el derecho de usar dicha informaci&oacute;n general, a fin de establecer criterios que mejoren los contenidos de este sistema, en todo caso siempre disociados de la persona que dej&oacute; los datos en su navegaci&oacute;n. <br />

b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Mecanismos Manuales: Son requerimientos formales y expresos de informaci&oacute;n a los suscriptores, usuarios y/o visitantes del portal que implican la recolecci&oacute;n de datos como nombre, apellidos, domicilio, correo electr&oacute;nico, ocupaci&oacute;n, etc.</p>
<p align="justify"><strong>II. EN CUANTO A LA ENTREGA DE INFORMACI&Oacute;N A TERCEROS</strong></p>
<p align="justify">Respecto de la entrega de informaci&oacute;n recopilada por medio de los mecanismos autom&aacute;ticos antes se&ntilde;alados, y que no contengan identificaci&oacute;n personal de los suscriptores, usuarios y/o visitantes de la p&aacute;gina, esta podr&aacute; ser utilizada para informar a entidades p&uacute;blicas, gubernamentales o a terceros sobre patrones de actividad, navegaci&oacute;n, audiencia y caracterizaci&oacute;n general de este sistema. Cuando se trate de datos recopilados que contengan informaci&oacute;n personal de los usuarios y/o visitantes de la p&aacute;gina, s&oacute;lo podr&aacute; entregarse en raz&oacute;n de un mandato legal o una orden emanada de los Tribunales de Justicia que as&iacute; lo establezca.</p>

<p align="justify">Al acceder al portal, el visitante tendr&aacute; derecho a revisar toda la informaci&oacute;n que est&eacute; disponible en el, solo pudiendo utilizarla para fines particulares y no comerciales. Sin perjuicio de lo anterior, esta repartici&oacute;n, no se hace responsable por la veracidad o exactitud de la informaci&oacute;n contenida en los enlaces a otros sitios Web o que haya sido entregada por terceros.</p>
<p align="justify"><strong>III. RECOLECCI&Oacute;N DE DATOS PERSONALES EN CUANTO A LAS SOLICITUDES DE INFORMACI&Oacute;N P&Uacute;BLICA DESTINADAS A ESTE ORGANISMO</strong></p>
<p align="justify">E&nbsp;asegura la confidencialidad de los datos personales de los solicitantes que se registren como tales en el sitio del sistema y dirigidas exclusivamente el entidad_padre mediante el(los) formulario(s) establecido(s) para esos efectos. Sin perjuicio de sus facultades legales, s&oacute;lo se efectuar&aacute; tratamiento de datos personales respecto de aquellos que han sido entregados voluntariamente por los Usuarios en el referido formulario.<br />

Los datos personales de los solicitantes ser&aacute;n utilizados &uacute;nicamente para el cumplimiento de los fines indicados en el(los) formulario(s) correspondiente(s) y siempre dentro de la competencia y atribuciones del organismo.<br />
Respecto de los datos personales, si en raz&oacute;n de las consultas o peticiones efectuadas por los solicitantes, &eacute;stos entregan datos personales al Sistema, &eacute;ste se entender&aacute; autorizado para su tratamiento en el marco de lo establecido en la ley 19.628 sobre &quot;Protecci&oacute;n de Datos de Car&aacute;cter Personal&quot;. Tales datos ser&aacute;n protegidos de acuerdo a la ley, y podr&aacute;n ser utilizados y transmitidos &uacute;nica y exclusivamente a otros organismos o dependencias p&uacute;blicas por&nbsp;este servicio p&uacute;blico&nbsp;en su calidad de administrador del sitio, no pudiendo acceder al contenido de los mismos.</p>

<p align="justify"><strong>IV. LIBERACI&Oacute;N DE RESPONSABILIDAD POR PARTE DE LOS ORGANISMOS DEL ESTADO </strong></p>
<p align="justify">El Sistema de Gesti&oacute;n de Solicitudes para la Ley N&deg;20.285 es un medio que facilita la realizaci&oacute;n de las solicitudes de acceso a la informaci&oacute;n p&uacute;blica, sin intervenir en la ejecuci&oacute;n de dichos actos ni intervenir ni formal ni sustantivamente en ninguna de sus fases. Tampoco el Sistema ser&aacute; responsable de la seriedad e idoneidad de las solicitudes recibidas, las que deber&aacute;n ser evaluadas por cada organismo adscrito al Sistema.</p>
<p align="justify"><strong>V. DECLARACI&Oacute;N </strong></p>

<p align="justify">Los usuarios del Sistema declaran conocer y aceptar la circunstancia relativa a que&nbsp;este servicio p&uacute;blico&nbsp;podr&aacute; en cualquier momento modificar el todo o parte de las presentes condiciones de uso, conforme la legislaci&oacute;n vigente o pol&iacute;ticas del organismo.</p>